apiVersion: v1
kind: Service
metadata:
  name: pg-deployment
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - name: pg-svc-port
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30023
