apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterlab
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kudalanfs/juypterlab
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kudala-storage
