apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterlab-pvc
  #namespace: jlab
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: kudala-storage

