kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jup-storage
provisioner: kubernetes.io/azure-file
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  skuName: Premium_LRS
mountOptions:
- dir_mode=0755
- file_mode=0600
- uid=1000
- gid=100
- mfsymlinks
- nobrl
