apiVersion: v1
kind: PersistentVolume
metadata:
  name: nifi
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kudalanfs/nifi 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kudala-storage

