apiVersion: v1
kind: Service
metadata:
  name: apache-nifi
spec:
  type: NodePort
  selector:
    app: nifi
  ports:
    - name: port1
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30022
    - name: port2
      protocol: TCP
      port: 55555
      targetPort: 55555
      nodePort: 30044
