kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: nifi-storage
provisioner: kubernetes.io/azure-file
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  skuName: Premium_LRS
