apiVersion: v1
kind: Service
metadata:
  name: mqtt
  labels:
    app: mqtt
spec:
  type: NodePort
  ports:
  - name: port1
    port: 1883
    protocol: TCP
    targetPort: 1883
    nodePort: 30027
  - name: port2
    port: 9001
    protocol: TCP
    targetPort: 9001
    nodePort: 30028
  selector:
    app: mqtt

