apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kudalanfs/kafka/data
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kudala-storage

