apiVersion: v1
kind: PersistentVolume
metadata:
  name: zooconf
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kudalanfs/zoo/conf
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kudala-storage

