apiVersion: v1
kind: PersistentVolume
metadata:
  name: graf2
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kudalanfs/grafana
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kudala-storage

