kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafanacprovisioning
spec:
  storageClassName: kudala-storage
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
