apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafanaclog
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kudalanfs/grafana/grafanaC/log
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kudala-storage

