apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafanachome
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kudalanfs/grafana/grafanaC/home
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kudala-storage

