apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafanabcustom
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kudalanfs/grafana/grafanaB/custom
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kudala-storage

