apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafanaacustom
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kudalanfs/grafana/grafanaA/custom
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kudala-storage

