apiVersion: v1
kind: Service
metadata:
  name: grafana-b
  labels:
    app: grafana-b
  annotations:
          #cloud.google.com/neg: '{"ingress": true}'
spec:
  type: NodePort
  selector:
    app: grafana-b
  ports:
    - name: grafana-b
      protocol: TCP
      port: 3101
      targetPort: 3000
      nodePort: 30202
