apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafanacprovisioning
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/kudalanfs/grafana/grafanaC/provisioning
  persistentVolumeReclaimPolicy: Retain
  storageClassName: kudala-storage

