apiVersion: v1
kind: PersistentVolume
metadata:
  name: jp1
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/kudalanfs/sts/jupyterlab
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sts-sc
