apiVersion: v1
kind: Service
metadata:
  name: jupyterlab-headless
  labels:
    app: jupyterlab
spec:  
 ports: 
 - port: 8888
   name: jupyterlab
 clusterIP: None
 selector:
   app: jupyterlab
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jupyterlab
spec:
  serviceName: "jupyterlab-headless"
  replicas: 2
  selector:
    matchLabels:
      app: jupyterlab
  template:
    metadata:
      labels:
        app: jupyterlab
    spec:
      securityContext:
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: jupyterlab
        image: jupyter/datascience-notebook:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
        command:
	  - /bin/bash
	  - -c
	  - |
            start.sh jupyter lab --LabApp.token='k8De*o9s1' --LabApp.ip='0.0.0.0' --LabApp.allow_root=True
        volumeMounts:
          - name: jup-claim
            mountPath: /home/jovyan
---

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jup-claim
spec:
  storageClassName: sts-sc
  accessModes:
  - ReadWriteMany 
  resources:
    requests:
      storage: 20Gi

